# Generated by Django 3.2.6 on 2021-08-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyApp', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('OPTION', 'OPTION'), ('MULTIOPTION', 'MULTIOPTION')], default='TEXT', max_length=200),
        ),
    ]
